apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: ${cluster_dns}
  labels:
    kops.k8s.io/cluster: ${cluster_dns}
spec:
  cloudProvider: aws
  kubernetesVersion: ${k8s_version}
  masterPublicName: ${cluster_dns}
  masterInternalName: ${cluster_dns}
  networkID: ${vpc_id}
  networkCIDR: ${vpc_cidr}
  awsRegion: ${aws_region}
  dnsZone: ${cluster_zone_id}
  nonMasqueradeCIDR: ${cluster_cidr}
  configBase: s3://${kops_bucket_name}/${cluster_dns}
%{ if length(api_access) > 0 ~}
  kubernetesApiAccess:
%{ for cidr in api_access ~}
  - ${cidr}
%{ endfor ~}
%{ endif ~}
%{ if length(ssh_access) > 0 ~}
  sshAccess:
%{ for cidr in ssh_access ~}
  - ${cidr}
%{ endfor ~}
%{ endif ~}
%{ if length(addons) > 0 ~}
  addons:
%{ for addon in addons ~}
  - manifest: ${addon}
%{ endfor ~}
%{ endif ~}
  networking:
    calico:
      majorVersion: v3
%{ if additional_master_policies != "" ~}
  additionalPolicies:
    master: |
      ${additional_master_policies}
%{ endif ~}
%{ if has_external_policies ~}
  externalPolicies:
    master:
%{ for policy in external_master_policies ~}
    - ${policy}
%{ endfor ~}
%{ endif ~}
  api:
%{ if lb_create ~}
    loadBalancer:
      type: ${lb_type}
      sslCertificate: ${certificate_arn}
      additionalSecurityGroups: [${lb_security_groups}]
%{ else ~}
    dns: {}
%{ endif ~}
  kubeAPIServer:
    maxRequestsInflight: ${max_requests_in_flight}
    maxMutatingRequestsInflight: ${max_mutating_requests_in_flight}
%{ if openid_connect_enabled ~}
    oidcIssuerURL: ${oidc_issuer_url}
    oidcClientID: ${oidc_client_id}
    oidcUsernameClaim: ${oidc_username_claim}
    oidcUsernamePrefix: "${oidc_username_prefix}"
    oidcGroupsClaim: ${oidc_groups_claim}
    oidcGroupsPrefix: "${oidc_groups_prefix}"
    oidcCAFile: /etc/ssl/certs/oidc-issuer-ca
%{ if length(oidc_required_claims) > 0 ~}
    oidcRequiredClaim:
%{ for claim in oidc_required_claims ~}
    - "${claim.key}=${claim.value}"
%{ endfor ~}
%{ endif ~}
%{ endif ~}
  kubelet:
    anonymousAuth: false
  docker:
    logDriver: json-file
    logOpt:
    - max-size=32m
    - max-file=12
  kubeProxy:
    cpuRequest: 80m
    memoryRequest: 128Mi
  channel: stable
  cloudLabels:
    Cluster: ${cluster_name}
    Namespace: ${namespace}
    Stage: ${stage}
    Region: ${region}
    kops.k8s.io/cluster: ${cluster_dns}
%{ if oidc_ca_file != "" ~}
  fileAssets:
  - name: oidc-issuer-ca
    path: /etc/ssl/certs/oidc-issuer-ca
    roles: [Master]
    content: |
      ${indent(6, file(oidc_ca_file))}
%{ endif ~}
  etcdClusters:
  - etcdMembers:
%{ for index, member in etcd_members ~}
    - encryptedVolume: true
      instanceGroup: ${member}
      name: master-${index}
      volumeType: ${etcd_main_volume_type}
      volumeSize: ${etcd_main_volume_size}
%{ if etcd_main_volume_iops != 0 ~}
      volumeIops: ${etcd_main_volume_iops}
%{ endif ~}
%{ endfor ~}
    name: main
    version: ${etcd_version}
    enableEtcdTLS: true
  - etcdMembers:
%{ for index, member in etcd_members ~}
    - encryptedVolume: true
      instanceGroup: ${member}
      name: master-${index}
      volumeType: ${etcd_event_volume_type}
      volumeSize: ${etcd_event_volume_size}
%{ if etcd_main_volume_iops != 0 ~}
      volumeIops: ${etcd_event_volume_iops}
%{ endif ~}
%{ endfor ~}
    name: events
    version: ${etcd_version}
    cpuRequest: 120m
    memoryRequest: 156Mi
    enableEtcdTLS: true
  subnets:
%{ for index, id in public_subnet_ids ~}
  - id: ${id}
    cidr: ${element(public_subnet_cidrs, index)}
    name: utility-${element(aws_zones, index)}
    type: Utility
    zone: ${element(aws_zones, index)}
%{ endfor ~}
%{ for index, id in private_subnet_ids ~}
  - id: ${id}
    cidr: ${element(private_subnet_cidrs, index)}
    name: private-${element(aws_zones, index)}
    type: Private
    zone: ${element(aws_zones, index)}
%{ endfor ~}
  topology:
    dns:
      type: ${dns_type}
    masters: private
    nodes: private
    bastion:
      idleTimeoutSeconds: 900
%{ if bastion_public_name != "" ~}
      bastionPublicName: ${bastion_public_name}.${cluster_dns}
%{ endif ~}
