apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: aws-iam-authenticator
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-iam-authenticator
