apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: ${instance_name}-${aws_availability_zone}
  labels:
    kops.k8s.io/cluster: ${cluster_name}
    kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
spec:
  #additionalUserData:
  #- name: reserved-resources.sh
  #  type: text/x-shellscript
  #  content: |
  #    #!/bin/sh
  #    
  cloudLabels:
    Cluster: ${cluster_name}
    Namespace: ${namespace}
    Stage: ${stage}
    Region: ${region}
    Role: ${instance_name}
    kops.k8s.io/cluster: ${cluster_name}
    kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
    kubernetes.io/cluster/${cluster_name}: owned
    k8s.io/cluster-autoscaler/${autoscaler}: ""
    k8s.io/cluster-autoscaler/node-template/label/instance_type: ${instance_name}
    k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
  image: ${image}
  machineType: ${instance_type}
  maxSize: ${instance_max}
  minSize: ${instance_min}
  maxPrice: "${autospotting_max_price}"
  rootVolumeSize: ${storage_in_gb}
  rootVolumeType: ${storage_type}
  rootVolumeIops: ${storage_iops}
  associatePublicIp: ${public_ip}
  nodeLabels:
    Cluster: ${cluster_name}
    Namespace: ${namespace}
    Stage: ${stage}
    Region: ${region}
    Role: ${instance_name}
    kops.k8s.io/cluster: ${cluster_name}
    kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
    original_machine_type: ${instance_type}
    instance_type: ${instance_name}
    spot: "${autospotting_enabled}"
  role: ${node_role}
  subnets: ${aws_subnet_id}
