apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${cluster_name}
  name: ${instance_type}-${aws_availability_zone}
spec:
  cloudLabels:
    Cluster: ${cluster_name}
    Namespace: ${namespace}
    Stage: ${stage}
    Region: ${region}
    spot-enabled: "${autospotting_enabled}"
    autospotting_min_on_demand_number: "${autospotting_min_on_demand}"
    kubernetes.io/cluster/${cluster_name}: owned
    k8s.io/cluster-autoscaler/${autoscaler}: ""
    k8s.io/cluster-autoscaler/node-template/label/instance_type: ${instance_type}
    k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup: ${instance_type}-${aws_availability_zone}
  image: ${image}
  machineType: ${instance_type}
  maxSize: ${instance_max}
  minSize: ${instance_min}
  nodeLabels:
    kops.k8s.io/instancegroup: ${instance_type}-${aws_availability_zone}
    instance_type: ${instance_type}
  role: ${node_role}
  subnets:
  - ${aws_availability_zone}
