apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${cluster_name}
  name: ${instance_name}-${aws_availability_zone}
spec:
  cloudLabels:
    Cluster: ${cluster_name}
    Namespace: ${namespace}
    Stage: ${stage}
    Region: ${region}
    role: ${instance_name}
    kubernetes.io/cluster/${cluster_name}: owned
    k8s.io/cluster-autoscaler/${autoscaler}: ""
    k8s.io/cluster-autoscaler/node-template/label/instance_type: ${instance_name}
    k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
  image: ${image}
  machineType: ${instance_type}
  maxSize: ${instance_max}
  minSize: ${instance_min}
  maxPrice: "${autospotting_max_price}"
  rootVolumeSize: ${storage_in_gb}
  rootVolumeType: ${storage_type}
  rootVolumeIops: ${storage_iops}
  nodeLabels:
    kops.k8s.io/instancegroup: ${instance_name}-${aws_availability_zone}
    instance_type: ${instance_name}
    spot: "${autospotting_enabled}"
  role: ${node_role}
  subnets:
  - ${aws_availability_zone}
